parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/**/{Migrations}'
            - '../src/helpers.php'

    App\Infrastructure\SymfonyCommandBus:
        arguments: ['@command.bus']
        lazy: true

    App\Infrastructure\SymfonyAggregateEventsBus:
        arguments: ['@aggregate_event.bus']
        lazy: true

    App\Infrastructure\SymfonyDomainEventBus:
        arguments: ['@domain_event.bus']
        lazy: true

    App\Ui\Http\Controller\:
        resource: '../src/Ui/Http/Controller/'
        tags: ['controller.service_arguments']
