parameters:
    env(AWS_REGION): eu-west-1

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $emailNotifierTo: '%env(csv:EMAIL_NOTIFIER_TO)%'
            $emailNotifierFrom: '%env(EMAIL_NOTIFIER_FROM)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/**/{Migrations}'
            - '../src/helpers.php'

    App\Infrastructure\SymfonyCommandBus:
        arguments: ['@command.bus']
        lazy: true

    App\Infrastructure\SymfonyAggregateEventsBus:
        arguments: ['@aggregate_event.bus']
        lazy: true

    App\Infrastructure\SymfonyDomainEventBus:
        arguments: ['@domain_event.bus']
        lazy: true

    App\Ui\Http\Controller\:
        resource: '../src/Ui/Http/Controller/'
        tags: ['controller.service_arguments']

    async_aws.http_client:
        class: Symfony\Component\HttpClient\CurlHttpClient
        arguments:
            - { timeout: 5, max_duration: 20 }

    AsyncAws\SecretsManager\SecretsManagerClient:
        arguments:
            - { region: '%env(AWS_REGION)%' }
            - ~
            - '@async_aws.http_client'
            - '@logger'

    App\Infrastructure\AwsSecretsManagerEnvVarProcessor:
        arguments:
            - '@AsyncAws\SecretsManager\SecretsManagerClient'
