imports:
    - { resource: backend.php }

parameters:
    env(EMAIL_NOTIFIER_TO): ''
    env(EMAIL_NOTIFIER_FROM): ''

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $emailNotifierTo: '%env(csv:EMAIL_NOTIFIER_TO)%'
            $emailNotifierFrom: '%env(EMAIL_NOTIFIER_FROM)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Infrastructure/{Postgres,DynamoDb,EventStoreDb}/'
            - '../src/Ui/Cli/CreateDynamoDbSchemaCommand.php'
            - '../src/helpers.php'

    App\Infrastructure\SymfonyCommandBus:
        arguments: ['@command.bus']
        lazy: true

    App\Infrastructure\SymfonyAggregateEventsBus:
        arguments: ['@aggregate_event.bus']
        lazy: true

    App\Infrastructure\SymfonyDomainEventBus:
        arguments: ['@domain_event.bus']
        lazy: true

    App\Ui\Http\Controller\:
        resource: '../src/Ui/Http/Controller/'
        tags: ['controller.service_arguments']
