parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/**/{Migrations}'

    App\Ui\Cli\Command\:
        resource: '../src/Ui/Cli/Command'

    App\Ui\Http\Controller\:
        resource: '../src/Ui/Http/Controller/'
        tags: ['controller.service_arguments']
