version: '3.8'

services:
  web:
    image: docker.io/bref/fpm-dev-gateway:1.4.2
    container_name: our-wedding-web
    ports:
      - 8080:80
    volumes:
      - ../app/public:/var/task/public
    depends_on:
      - php
    networks:
      - app
    environment:
      HANDLER: public/index.php
      DOCUMENT_ROOT: public

  php:
    image: ghcr.io/eddmann/our-wedding-app:dev-dda968d
    #build:
    #  context: ../
    #  dockerfile: docker/Dockerfile
    container_name: our-wedding-php
    volumes:
      - ../app:/var/task
    depends_on:
      - postgres
    networks:
      - app
    environment:
      APP_ENV: dev
      APP_SECRET: secret
      DATABASE_URL: 'postgresql://user:password@postgres:5432/db?serverVersion=14.1&charset=utf8'
      MAILER_DSN: 'smtp://mailhog:1025'
      EMAIL_NOTIFIER_TO: 'to@email.com'
      EMAIL_NOTIFIER_FROM: 'from@email.com'
      ADMIN_PASSWORD: password
      PAGE_CONTENT: '{}'

  postgres:
    image: docker.io/postgres:14.1-alpine3.14
    container_name: our-wedding-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      POSTGRES_INITDB_ARGS: '--auth-host=md5'
      TZ: Europe/London

  mailhog:
    image: docker.io/mailhog/mailhog:v1.0.1
    container_name: our-wedding-mailhog
    ports:
      - 8025:8025
    networks:
      - app

volumes:
  postgres:
    driver: local

networks:
  app:
