service: our-wedding-website

variablesResolutionMode: 20210326

custom:
    tags:
        Service: OurWedding
        Application: Website
        Env: ${self:provider.stage}

provider:
    name: aws
    region: ${opt:region}
    stage: ${opt:stage}
    runtime: provided.al2
    memorySize: 512
    vpc:
        securityGroupIds:
            - ${ssm:/our-wedding/${self:provider.stage}/network/default-security-group-id}
        subnetIds: ${ssm:/our-wedding/${self:provider.stage}/network/private-subnet-ids}
    tags: ${self:custom.tags}
    stackTags: ${self:custom.tags}
    deploymentBucket:
        tags: ${self:custom.tags}
        blockPublicAccess: true
    lambdaHashingVersion: 20201221
    httpApi:
        useProviderTags: true
    iamManagedPolicies:
        - ${ssm:/our-wedding/${self:provider.stage}/apps/website/policy-arn}
    environment:
        APP_ENV: prod
        APP_SECRET: 'sm:/our-wedding/${self:provider.stage}/apps/website/app-secret'
        PROXY_AUTH_KEY_HEADER: '${ssm:/our-wedding/${self:provider.stage}/apps/website/origin-domain-auth-key-header}'
        PROXY_AUTH_KEY_VALUE: '${ssm:/aws/reference/secretsmanager//our-wedding/${self:provider.stage}/apps/website/origin-domain-auth-key}'
        HOST: '${ssm:/our-wedding/${self:provider.stage}/apps/website/host}'
        HTTPS: true
        TRUSTED_PROXIES: '127.0.0.1'
        MESSENGER_ASYNC_TRANSPORT_DSN: '${ssm:/our-wedding/${self:provider.stage}/apps/website/worker-queue-url}'
        DYNAMODB_SESSIONS_TABLE: '${ssm:/our-wedding/${self:provider.stage}/apps/website/sessions-table-name}'
        DATABASE_URL: 'sm:/our-wedding/${self:provider.stage}/data/website/db-url'
        MAILER_DSN: 'sm:/our-wedding/${self:provider.stage}/apps/website/mailer-dsn'
        EMAIL_NOTIFIER_TO: '${ssm(raw):/our-wedding/${self:provider.stage}/apps/website/email-notifier-to}'
        EMAIL_NOTIFIER_FROM: '${ssm:/our-wedding/${self:provider.stage}/apps/website/email-notifier-from}'
        ADMIN_PASSWORD: 'sm:/our-wedding/${self:provider.stage}/apps/website/admin-password'
        PAGE_CONTENT: 'sm:/our-wedding/${self:provider.stage}/apps/website/page-content'

plugins:
    - ./vendor/bref/bref

functions:
    web:
        handler: public/index.php
        timeout: 28
        layers:
            - ${bref:layer.php-81-fpm}
        events:
            - httpApi: '*'
    worker:
        handler: bin/worker.php
        timeout: 120
        layers:
            - ${bref:layer.php-81}
        events:
            - sqs:
                  arn: '${ssm:/our-wedding/${self:provider.stage}/apps/website/worker-queue-arn}'
                  batchSize: 1
    console:
        handler: bin/console
        timeout: 120
        layers:
            - ${bref:layer.php-81}
            - ${bref:layer.console}

package:
    patterns:
        - '!src/Ui/Http/Asset/**'
        - '!node_modules/**'
        - '!public/build/**'
        - '!tests/**'
        - '!var/**'
        - 'var/cache/prod/**'
        - 'public/build/entrypoints.json'
        - 'public/build/manifest.json'
