service: our-wedding

custom:
    tags:
        Service: OurWedding
        Stage: ${self:provider.stage}

provider:
    name: aws
    region: ${opt:region}
    stage: ${opt:stage}
    runtime: provided.al2
    memorySize: 512
    tags: ${self:custom.tags}
    stackTags: ${self:custom.tags}
    endpointType: regional # use own CloudFront distro.
    deploymentBucket:
        tags: ${self:custom.tags}
        blockPublicAccess: true
    environment:
        APP_ENV: prod
        APP_SECRET: 'sm:/our-wedding/${self:provider.stage}/apps/website/app-secret'
        PROXY_AUTH_KEY_HEADER: '${ssm:/our-wedding/${self:provider.stage}/apps/website/origin-domain-auth-key-header}'
        PROXY_AUTH_KEY_VALUE: '${ssm:/aws/reference/secretsmanager//our-wedding/staging/apps/website/origin-domain-auth-key}'
        DATABASE_URL: 'sm:/our-wedding/${self:provider.stage}/data/website/db-url'
        MAILER_DSN: 'sm:/our-wedding/${self:provider.stage}/apps/website/mailer-dsn'
        EMAIL_NOTIFIER_TO: '${ssm:/our-wedding/${self:provider.stage}/apps/website/email-notifier-to}'
        EMAIL_NOTIFIER_FROM: '${ssm:/our-wedding/${self:provider.stage}/apps/website/email-notifier-from}'
        ADMIN_PASSWORD: 'sm:/our-wedding/${self:provider.stage}/apps/website/admin-password'
        PAGE_CONTENT: '${ssm:/our-wedding/${self:provider.stage}/apps/website/page-content}'

plugins:
    - ./vendor/bref/bref

functions:
    web:
        handler: public/index.php
        timeout: 29
        layers:
            - ${bref:layer.php-81-fpm}
        events:
            - httpApi: '*'
    console:
        handler: bin/console
        timeout: 120
        layers:
            - ${bref:layer.php-81}
            - ${bref:layer.console}

package:
    patterns:
        - '!src/Ui/Http/Asset/**'
        - '!node_modules/**'
        - '!public/build/**'
        - '!tests/**'
        - '!var/**'
        - 'var/cache/prod/**'
        - 'public/build/entrypoints.json'
        - 'public/build/manifest.json'
