apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.secrets.postgresPassword | quote }}
  dsn: {{ (printf "postgresql://postgres:%s@postgres:5432/our-wedding?serverVersion=10.18&charset=utf8" .Values.secrets.postgresPassword) | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.secrets.rabbitmqPassword | quote }}
  dsn: {{ (printf "amqp://rabbitmq:%s@rabbitmq:5672/%%2f/async?auto_setup=true" .Values.secrets.rabbitmqPassword) | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: app
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData: {{ .Values.secrets | toYaml | nindent 2 }}
