apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: worker
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
        - name: {{ .Values.app.imagePullSecret }}
      containers:
        - name: worker
          image: {{ .Values.app.image | quote }}
          imagePullPolicy: Always
          env:
          {{- range $name, $item := .Values.app.env }}
            - name: {{ $name }}
              {{- $item | toYaml | nindent 14 }}
          {{- end }}
            - name: CONTAINER_ROLE
              value: worker
