parameters:
    env(DYNAMODB_SESSIONS_TABLE): ''

services:
    AsyncAws\DynamoDbSession\SessionHandler:
        arguments:
            - '@AsyncAws\DynamoDb\DynamoDbClient'
            - table_name: '%env(DYNAMODB_SESSIONS_TABLE)%'
