parameters:
    env(MESSENGER_ASYNC_TRANSPORT_DSN): ''

framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_ASYNC_TRANSPORT_DSN)%'
                options:
                    auto_setup: false
        routing:
            App\Domain\Helpers\DomainEvent: async

services:
    Bref\Symfony\Messenger\Service\Sqs\SqsConsumer:
        public: true
        autowire: true
        arguments:
            $bus: '@messenger.routable_message_bus'
            $transportName: 'async'
