framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_ASYNC_TRANSPORT_DSN)%'
                options:
                    auto_setup: false
        routing:
            App\Domain\Helpers\DomainEvent: async

services:
    bref.messenger.sqs_client:
        class: AsyncAws\Sqs\SqsClient
        public: true
        arguments:
            - { region: '%env(AWS_REGION)%' }
            - ~
            - '@async_aws.http_client'
            - '@logger'

    Bref\Symfony\Messenger\Service\Sqs\SqsConsumer:
        public: true
        autowire: true
        arguments:
            $bus: '@messenger.routable_message_bus'
            $transportName: 'async'
