services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Infrastructure\Postgres\:
        resource: '../../src/Infrastructure/Postgres/'
        exclude:
            '../../src/Infrastructure/Postgres/Migrations'
