framework:
    messenger:
        reset_on_message: true
        default_bus: command.bus
        buses:
            command.bus:
            aggregate_event.bus:
                default_middleware: allow_no_handlers
            domain_event.bus:
                default_middleware: allow_no_handlers
        transports:
            sync: 'sync://'
            async: 'sync://'
        routing:
            App\Domain\Helpers\AggregateEvents: sync
            App\Domain\Helpers\DomainEvent: sync
