framework:
    messenger:
        reset_on_message: true
        default_bus: command.bus
        buses:
            command.bus:
            aggregate_event.bus:
                default_middleware: allow_no_handlers
            domain_event.bus:
                default_middleware: allow_no_handlers
        transports:
            sync: 'sync://'
            async: 'sync://'
        routing:
            App\Domain\Helpers\AggregateEvents: sync
            App\Domain\Helpers\DomainEvent: sync

when@prod:
    parameters:
        env(MESSENGER_ASYNC_TRANSPORT_DSN): ''

    framework:
        messenger:
            transports:
                async:
                    dsn: '%env(MESSENGER_ASYNC_TRANSPORT_DSN)%'
                    options:
                        auto_setup: false
            routing:
                App\Domain\Helpers\DomainEvent: async

    services:
        Bref\Symfony\Messenger\Service\Sqs\SqsConsumer:
            public: true
            autowire: true
            arguments:
                $bus: '@messenger.routable_message_bus'
                $transportName: 'async'
