monolog:
    channels: ['info']

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!info", "!event"]
            info:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                channels: ["info"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!info", "!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            info:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                channels: ["info"]

when@prod:
    monolog:
        channels: [deprecation]
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
                channels: ["!info"]
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            info:
                type: stream
                path: php://stderr
                formatter: monolog.formatter.json
                channels: ["info"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
