name: Test

on:
  push:
    branches-ignore:
      - main
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Restore Composer cache
        uses: actions/cache@v2
        with:
          path: ./app/vendor
          key: test-composer-${{ hashFiles('./app/composer.lock') }}
          restore-keys: test-composer-
      - name: Restore Yarn cache
        uses: actions/cache@v2
        with:
          path: ./app/node_modules
          key: test-yarn-${{ hashFiles('./app/yarn.lock') }}
          restore-keys: test-yarn-
      - name: Start
        run: make start
      - name: Test
        run: make can-release
